export const ACTIVE_ICON = 'ACTIVE_ICON';
export const USER_TYPE = 'USER_TYPE';
export const SELLER_USER_TYPE = 'SELLER_USER_TYPE';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const REGISTER_DETAILS = 'REGISTER_DETAILS';
export const REGISTER_SELLER_ADDITIONAL_DETAILS = 'REGISTER_SELLER_ADDITIONAL_DETAILS';
export const RESEND_OTP = 'RESEND_OTP';
export const ADDRESS_UPDATE ='ADDRESS_UPDATE';
export const FORGOT_PASSWORD_DETAILS = 'FORGOT_PASSWORD_DETAILS';
export const LISTING_TITLE ='LISTING_TITLE';
export const DISPLAY_REGION_NAME = 'DISPLAY_REGION_NAME';
export const DISPLAY_VARIETY_NAME = 'DISPLAY_VARIETY_NAME';
export const DISPLAY_ORDER_NUMBER = 'DISPLAY_ORDER_NUMBER';
export const FILTER_FEATURED_DATA = 'FILTER_FEATURED_DATA';
export const FILTER_ORIGINS_DATA = 'FILTER_ORIGINS_DATA';
export const FILTER_NANO_LOT_DATA = 'FILTER_NANO_LOT_DATA';
export const FILTER_MICRO_LOT_DATA = 'FILTER_MICRO_LOT_DATA';
export const FILTER_VARITIES_DATA = 'FILTER_VARITIES_DATA';
export const BUY_PRODUCT = 'BUY_PRODUCT';
export const PRODUCT_CART_DETAILS = 'PRODUCT_CART_DETAILS';
export const SPINNER_SWITCH = 'SPINNER_SWITCH';
////////////////////////////////////////

export const PROCEED_CLICKED = 'PROCEED_CLICKED';
export const EDIT_CUSTOMER_INFO ='EDIT_CUSTOMER_INFO';
export const ACTIVE_TAB ='ACTIVE_TAB';